GET http://localhost:8899/api/article
###
POST http://localhost:8899/api/article
Content-Type: application/json

{
  "subject" : "test",
  "writer" : "test",
  "content" : "test"
}

###
DELETE http://localhost:8899/api/article/12

###
GET http://localhost:8899/api/article/12

###
GET http://localhost:8899/api/article/11

###

PUT http://localhost:8899/api/article/11
Content-Type: application/json

{
  "subject" : "aaa",
  "writer" : "sss",
  "content" : "mmm"
}